export enum RabbitMQ{
    UserQueue = 'users',
    ProductQueue = 'products',
    AuthQueue = 'auth'
}

export enum UserMsg {
    CREATE='CREATE_USER',
    FIND_ALL = 'FIND_USERS',
    FIND_ONE = 'FIND_USER',
    UPDATE = 'UPDATE_USER',
    DELETE= 'DELETE_USER',
    VALID_USER= 'VALID_USER',
    FIND_BY_EMAIL = 'FIND_USER_BY_EMAIL',
    FIND_BY_ID = 'FIND_USER_BY_ID',
}

export enum AuthMsg {
    LOGIN = 'LOGIN',
    REGISTER = 'REGISTER',
    VALIDATE_TOKEN = 'VALIDATE_TOKEN',
    REFRESH_TOKEN = 'REFRESH_TOKEN',
    LOGOUT = 'LOGOUT',
    FORGOT_PASSWORD = 'FORGOT_PASSWORD',
    RESET_PASSWORD = 'RESET_PASSWORD',
    CHANGE_PASSWORD = 'CHANGE_PASSWORD',
    VALIDATE_EMAIL = 'VALIDATE_EMAIL',
    SEND_VERIFICATION_EMAIL = 'SEND_VERIFICATION_EMAIL',
    SEND_RESET_PASSWORD_EMAIL = 'SEND_RESET_PASSWORD_EMAIL',
    SEND_CHANGE_PASSWORD_EMAIL = 'SEND_CHANGE_PASSWORD_EMAIL',
    SEND_EMAIL = 'SEND_EMAIL',
    SEND_EMAIL_VERIFICATION = 'SEND_EMAIL_VERIFICATION',   
}

export enum ProductMsg{
    CREATE='CREATE_PRODUCT',
    FIND_ALL = 'FIND_PRODUCTS',
    FIND_ONE = 'FIND_PRODUCT',
    UPDATE = 'UPDATE_PRODUCT',
    DELETE= 'DELETE_PRODUCT',
    FIND_BY_CATEGORY = 'FIND_PRODUCTS_BY_CATEGORY',
    FIND_BY_NAME = 'FIND_PRODUCTS_BY_NAME',
    FIND_BY_PRICE = 'FIND_PRODUCTS_BY_PRICE',
    FIND_BY_ID = 'FIND_PRODUCTS_BY_ID',
    FIND_BY_RATING = 'FIND_PRODUCTS_BY_RATING',
}